# Generated by Django 3.2.9 on 2021-12-04 21:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskUser',
            new_name='UserTask',
        ),
    ]
