# Generated by Django 3.2.9 on 2021-12-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_rename_taskuser_usertask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
