# Generated by Django 3.2.9 on 2021-12-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0005_auto_20211204_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='todolist',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='start_data',
            field=models.DateField(null=True),
        ),
    ]
